language: python
sudo: false

branches:
  only:
    - master
    - stable

python:

os:

matrix:
  include:
  - os: linux
    python:  "2.6"
  - os: linux
    python:  "2.7"
  - os: linux
    python:  "3.2"
  - os: linux
    python:  "3.3"
  - os: linux
    python:  "3.4"
  - os: linux
    python:  "3.5"
  - os: linux
    python:  "3.6"
  - os: linux
    python:  "3.5-dev" # 3.5 development branch
  - os: linux
    python:  "3.6-dev"
  - os: linux
    python:  "3.7-dev"
  - os: linux
    python: "pypy"  # PyPy2 2.5.0
  - os: linux
    python:  "pypy-5.3.1"
  - os: linux
    python:  "nightly" # currently points to 3.7-dev
  - os: osx
    osx_image: xcode7.2
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  allow_failure:
  - os: linux
    python:  "3.8-dev"
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: linux
    python:  "2.6"
  - os: linux
    python:  "3.2"
  - os: linux
    python: "pypy"
  - os: linux
    python:  "pypy3"
  - os: linux
    python:  "pypy-5.3.1"

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_retry brew tap homebrew/versions || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then if [ ${TRAVIS_OSX_IMAGE:-none} == xcode6.4 ] ; then travis_wait 30 brew upgrade || travis_retry brew upgrade || true ; else travis_wait brew upgrade || travis_retry brew upgrade || true ; fi ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python26 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait brew install python3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python34 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python35 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python36 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python27 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install coverage $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install codecov $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then export VERSIONER_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION:-2.7} || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then defaults write com.apple.versioner.python Version ${TRAVIS_PYTHON_VERSION:2.7} || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then for A_PYTHON_VERSION in 2.6 2.7 3.2 3.3 3.4 3.5 3.6 3.7 3.8 ; do ln -sf /usr/local/bin/python${A_PYTHON_VERSION} /usr/bin/python${A_PYTHON_VERSION} || true ; done ; fi
  - travis_retry pip install tox || pip install tox || true ;
  - travis_retry pip install coverage || true ;
  - travis_retry pip install codecov || true ;
  - travis_retry python -m pip install coverage || python -m pip install coverage || true ;
  - travis_retry python -m pip install codecov || python -m pip install codecov || true ;
  - travis_retry python3 -m pip install tox || python3 -m pip install tox || true ;
  - travis_retry python3 -m pip install coverage || python3 -m pip install coverage || true ;
  - travis_retry python3 -m pip install codecov || python3 -m pip install codecov || true ;
  - travis_retry python3 -m pip install -r requirements.txt || python3 -m pip install -r requirements.txt || true ;
  - make clean || exit $? ;

install: "make init"

script:
  - if [ $TRAVIS_OS_NAME == osx ] ; then echo "SKIP make test" ; else make test || exit $? ; fi
  - if [ $TRAVIS_OS_NAME == osx ] || [ $TRAVIS_PYTHON_VERSION == 3.2 ] ; then echo "SKIP codecov" ; else codecov || exit $? ; fi
  - make clean || exit $? ;
  - if [ $TRAVIS_PYTHON_VERSION == 3.2 ] ; then echo "SKIP tox" ; else make test-tox || exit $? ; fi

after_script:
  - make clean

after_success:
  - if [ $TRAVIS_OS_NAME == osx ] || [ $TRAVIS_PYTHON_VERSION == 3.2 ] ; then echo "SKIP codecov" ; else codecov || exit $? ; fi

